import { Node, Edge } from '@xyflow/react';
import { NODE_REGISTRY } from './nodeRegistry';

export interface HFAtoZGuide {
  summary: string;
  hfModelSlug: string;
  hardwareTier: string;
  stepByStep: string[];
  docUrl: string;
}

export interface WorkflowTemplate {
  id: string;
  name: string;
  category: 'chatbot' | 'image' | 'reasoning' | 'audio';
  description: string;
  iconName: string;
  badgeText: string;
  nodes: Node[];
  edges: Edge[];
  hfGuide?: HFAtoZGuide;
}

export const WorkflowTemplatesList: WorkflowTemplate[] = [
  {
    id: 'tpl_hf_free_all_ai',
    name: '🌟 Free Hugging Face AI Suite (LLM + FLUX.1 + MusicGen)',
    category: 'chatbot',
    description: 'Complete multi-modal AI workflow using 100% free Hugging Face models: Llama 3.3 70B for text reasoning, FLUX.1 Schnell for image art, and MusicGen for audio synthesis.',
    iconName: 'Sparkles',
    badgeText: 'Featured 100% Free AI',
    hfGuide: {
      summary: 'Multi-modal orchestration connecting Hugging Face Serverless Router (Llama 3.3 70B), FLUX.1 Schnell image generation, and MusicGen audio beats at zero cost.',
      hfModelSlug: 'meta-llama/Llama-3.3-70B-Instruct & black-forest-labs/FLUX.1-schnell',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Generate a free Access Token on huggingface.co/settings/tokens with "Inference" permission.',
        'Step B: Accept license terms on meta-llama/Llama-3.3-70B-Instruct if using gated Llama models.',
        'Step C: Connect inbound Telegram or WhatsApp webhook trigger from settings.',
        'Step D: Inbound prompts automatically branch: text questions route to Llama 3.3, art requests to FLUX.1, and music prompts to MusicGen.',
        'Step E: Visual workflow graph and execution outputs automatically commit to datasets/<username>/hf-workflow-data.',
      ],
      docUrl: 'https://huggingface.co/docs/api-inference/index',
    },
    nodes: [
      {
        id: 'node_tg_inbound',
        type: 'telegram_trigger',
        position: { x: 80, y: 180 },
        data: {
          label: 'Telegram Trigger',
          category: 'triggers',
          type: 'telegram_trigger',
          status: 'idle',
          subtitle: 'Bot Webhook Endpoint',
          config: NODE_REGISTRY.telegram_trigger.defaultConfig,
          inputs: NODE_REGISTRY.telegram_trigger.inputs,
          outputs: NODE_REGISTRY.telegram_trigger.outputs,
        },
      },
      {
        id: 'node_hf_llama',
        type: 'hf_router',
        position: { x: 440, y: 100 },
        data: {
          label: 'HuggingFace Router',
          category: 'models',
          type: 'hf_router',
          status: 'idle',
          subtitle: 'meta-llama/Llama-3.3-70B-Instruct',
          config: {
            ...NODE_REGISTRY.hf_router.defaultConfig,
            model_id: 'meta-llama/Llama-3.3-70B-Instruct',
            system_prompt: 'You are an intelligent, helpful AI assistant built with Hugging Face models.',
            user_prompt: '{{ $node["Telegram Trigger"].text }}',
          },
          inputs: NODE_REGISTRY.hf_router.inputs,
          outputs: NODE_REGISTRY.hf_router.outputs,
        },
      },
      {
        id: 'node_hf_flux',
        type: 'hf_image_gen',
        position: { x: 440, y: 260 },
        data: {
          label: 'FLUX.1 Schnell',
          category: 'models',
          type: 'hf_image_gen',
          status: 'idle',
          subtitle: 'black-forest-labs/FLUX.1-schnell',
          config: {
            ...NODE_REGISTRY.hf_image_gen.defaultConfig,
            model_id: 'black-forest-labs/FLUX.1-schnell',
            prompt_template: '{{ $node["Telegram Trigger"].text }}',
          },
          inputs: NODE_REGISTRY.hf_image_gen.inputs,
          outputs: NODE_REGISTRY.hf_image_gen.outputs,
        },
      },
      {
        id: 'node_tg_outbound',
        type: 'telegram_reply',
        position: { x: 860, y: 180 },
        data: {
          label: 'Telegram Reply',
          category: 'actions',
          type: 'telegram_reply',
          status: 'idle',
          subtitle: 'Send Response to Chat',
          config: {
            chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}',
            message_template: '🤖 **AI Response:**\n\n{{ $node["HuggingFace Router"].response_text }}\n\n🎨 **Generated Art:**\n{{ $node["FLUX.1 Schnell"].image_url }}',
          },
          inputs: NODE_REGISTRY.telegram_reply.inputs,
          outputs: NODE_REGISTRY.telegram_reply.outputs,
        },
      },
    ],
    edges: [
      {
        id: 'edge_tg_to_llama',
        source: 'node_tg_inbound',
        sourceHandle: 'text',
        target: 'node_hf_llama',
        targetHandle: 'user_prompt',
        type: 'customEdge',
        data: { color: '#38bdf8' },
      },
      {
        id: 'edge_tg_to_flux',
        source: 'node_tg_inbound',
        sourceHandle: 'text',
        target: 'node_hf_flux',
        targetHandle: 'prompt_template',
        type: 'customEdge',
        data: { color: '#ec4899' },
      },
      {
        id: 'edge_llama_to_out',
        source: 'node_hf_llama',
        sourceHandle: 'response_text',
        target: 'node_tg_outbound',
        targetHandle: 'text',
        type: 'customEdge',
        data: { color: '#8b5cf6' },
      },
    ],
  },
  {
    id: 'tpl_openclaw_telegram_agent',
    name: '🐾 OpenClaw Autonomous Telegram Agent',
    category: 'chatbot',
    description: 'Autonomous multi-tool personal AI agent hosted on Hugging Face Spaces (2 vCPU + 16GB RAM) with live Web Search, Python Sandbox, and Dataset Memory.',
    iconName: 'Bot',
    badgeText: 'OpenClaw • Free 2 vCPU',
    hfGuide: {
      summary: 'Runs OpenClaw agent runtime on a dedicated Hugging Face Space (2 vCPU + 16 GB RAM • $0/mo). Handles multi-step ReAct planning, live online search, Python execution, and private Hub dataset memory.',
      hfModelSlug: 'openclaw/openclaw',
      hardwareTier: 'Hugging Face Space (2 vCPU + 16 GB RAM • Free)',
      stepByStep: [
        'Step A: Duplicate the OpenClaw space via https://huggingface.co/spaces/openclaw/openclaw?duplicate=true.',
        'Step B: In Space Settings → Secrets, configure HF_TOKEN and optional TELEGRAM_BOT_TOKEN.',
        'Step C: In HF Workflow, the OpenClaw node connects via Gradio Client to your space endpoint.',
        'Step D: Inbound chat prompts trigger autonomous ReAct loops: Thought ➔ Action (Web/Python) ➔ Observation ➔ Final Answer.',
        'Step E: Conversational memory and execution transcripts sync to datasets/<username>/hf-workflow-data automatically.',
      ],
      docUrl: 'https://huggingface.co/spaces/openclaw/openclaw',
    },
    nodes: [
      {
        id: 'n1',
        type: 'telegram_trigger',
        position: { x: 80, y: 180 },
        data: {
          label: 'Telegram Trigger',
          category: 'triggers',
          type: 'telegram_trigger',
          status: 'idle',
          subtitle: 'Inbound tasks & questions',
          config: NODE_REGISTRY.telegram_trigger.defaultConfig,
          inputs: NODE_REGISTRY.telegram_trigger.inputs,
          outputs: NODE_REGISTRY.telegram_trigger.outputs,
        },
      },
      {
        id: 'n2',
        type: 'openclaw_agent',
        position: { x: 480, y: 180 },
        data: {
          label: 'OpenClaw Agent',
          category: 'models',
          type: 'openclaw_agent',
          status: 'idle',
          subtitle: 'openclaw/openclaw (Free HF Space)',
          config: {
            ...NODE_REGISTRY.openclaw_agent.defaultConfig,
            task_prompt: '{{ $node["Telegram Trigger"].text }}',
            agent_role: 'general_assistant',
          },
          inputs: NODE_REGISTRY.openclaw_agent.inputs,
          outputs: NODE_REGISTRY.openclaw_agent.outputs,
        },
      },
      {
        id: 'n3',
        type: 'telegram_reply',
        position: { x: 880, y: 180 },
        data: {
          label: 'Telegram Reply',
          category: 'actions',
          type: 'telegram_reply',
          status: 'idle',
          subtitle: 'Send Agent Response',
          config: {
            chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}',
            message_template: '{{ $node["OpenClaw Agent"].agent_response }}',
          },
          inputs: NODE_REGISTRY.telegram_reply.inputs,
          outputs: NODE_REGISTRY.telegram_reply.outputs,
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'n1', sourceHandle: 'text', target: 'n2', targetHandle: 'task_prompt', type: 'customEdge', data: { color: '#f97316' } },
      { id: 'e2', source: 'n2', sourceHandle: 'agent_response', target: 'n3', targetHandle: 'text', type: 'customEdge', data: { color: '#4ade80' } },
    ],
  },
  {
    id: 'tpl_openclaw_whatsapp_researcher',
    name: '🐾 OpenClaw WhatsApp Multi-Tool Researcher',
    category: 'chatbot',
    description: 'Autonomous research & Python developer assistant for WhatsApp powered by OpenClaw on Hugging Face Spaces.',
    iconName: 'Bot',
    badgeText: 'OpenClaw • Multi-Tool',
    hfGuide: {
      summary: 'Autonomous Python coding and factual web research assistant connecting Meta WhatsApp Cloud API directly to OpenClaw on Hugging Face Spaces.',
      hfModelSlug: 'openclaw/openclaw',
      hardwareTier: 'Hugging Face Space (2 vCPU + 16 GB RAM • Free)',
      stepByStep: [
        'Step A: Setup WhatsApp Cloud API on developers.facebook.com and paste credentials into Settings ➔ API Credentials.',
        'Step B: Deploy or duplicate OpenClaw Space with 2 vCPU on Hugging Face Hub.',
        'Step C: WhatsApp user questions trigger autonomous multi-step web research and Python sandbox calculations.',
        'Step D: Clean summaries and code outputs dispatch back to the user WhatsApp chat via WhatsApp Reply node.',
      ],
      docUrl: 'https://huggingface.co/docs/hub/spaces',
    },
    nodes: [
      {
        id: 'n1',
        type: 'whatsapp_trigger',
        position: { x: 80, y: 180 },
        data: {
          label: 'WhatsApp Trigger',
          category: 'triggers',
          type: 'whatsapp_trigger',
          status: 'idle',
          subtitle: 'Inbound WhatsApp questions',
          config: NODE_REGISTRY.whatsapp_trigger.defaultConfig,
          inputs: NODE_REGISTRY.whatsapp_trigger.inputs,
          outputs: NODE_REGISTRY.whatsapp_trigger.outputs,
        },
      },
      {
        id: 'n2',
        type: 'openclaw_agent',
        position: { x: 480, y: 180 },
        data: {
          label: 'OpenClaw Researcher',
          category: 'models',
          type: 'openclaw_agent',
          status: 'idle',
          subtitle: 'openclaw/openclaw (Free HF Space)',
          config: {
            ...NODE_REGISTRY.openclaw_agent.defaultConfig,
            task_prompt: '{{ $node["WhatsApp Trigger"].message_body }}',
            agent_role: 'deep_researcher',
          },
          inputs: NODE_REGISTRY.openclaw_agent.inputs,
          outputs: NODE_REGISTRY.openclaw_agent.outputs,
        },
      },
      {
        id: 'n3',
        type: 'whatsapp_reply',
        position: { x: 880, y: 180 },
        data: {
          label: 'WhatsApp Reply',
          category: 'actions',
          type: 'whatsapp_reply',
          status: 'idle',
          subtitle: 'Send Research Findings',
          config: {
            ...NODE_REGISTRY.whatsapp_reply.defaultConfig,
          },
          inputs: NODE_REGISTRY.whatsapp_reply.inputs,
          outputs: NODE_REGISTRY.whatsapp_reply.outputs,
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'n1', sourceHandle: 'message_body', target: 'n2', targetHandle: 'task_prompt', type: 'customEdge', data: { color: '#25d366' } },
      { id: 'e2', source: 'n2', sourceHandle: 'agent_response', target: 'n3', targetHandle: 'text', type: 'customEdge', data: { color: '#f59e0b' } },
    ],
  },
  {
    id: 'tpl_telegram_ai_bot',
    name: '🤖 Telegram AI Support Bot (Llama 3.3 70B)',
    category: 'chatbot',
    description: 'High-speed automated Telegram customer support chatbot using Meta Llama 3.3 70B Instruct with system prompt customization and state history.',
    iconName: 'Send',
    badgeText: 'Telegram • 100% Free',
    hfGuide: {
      summary: 'Zero-server Telegram AI support bot running Meta Llama 3.3 70B Instruct over Hugging Face free serverless router.',
      hfModelSlug: 'meta-llama/Llama-3.3-70B-Instruct',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Create your bot on Telegram via @BotFather and paste HTTP API Bot Token into Settings.',
        'Step B: Click "Register Telegram Webhook Automatically" in Settings ➔ Bots & Webhooks.',
        'Step C: Inbound messages route into Hugging Face Router with your tailored System Prompt.',
        'Step D: Model responses stream back to the Telegram chat in real time.',
      ],
      docUrl: 'https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct',
    },
    nodes: [
      {
        id: 'node_tg_trig',
        type: 'telegram_trigger',
        position: { x: 100, y: 200 },
        data: {
          label: 'Telegram Trigger',
          category: 'triggers',
          type: 'telegram_trigger',
          status: 'idle',
          subtitle: 'Webhook Inbound Receiver',
          config: {
            ...NODE_REGISTRY.telegram_trigger.defaultConfig,
            listen_commands: '/support, /help, /start',
          },
          inputs: NODE_REGISTRY.telegram_trigger.inputs,
          outputs: NODE_REGISTRY.telegram_trigger.outputs,
        },
      },
      {
        id: 'node_hf_llama_bot',
        type: 'hf_router',
        position: { x: 500, y: 200 },
        data: {
          label: 'HuggingFace Router',
          category: 'models',
          type: 'hf_router',
          status: 'idle',
          subtitle: 'meta-llama/Llama-3.3-70B-Instruct',
          config: {
            ...NODE_REGISTRY.hf_router.defaultConfig,
            model_id: 'meta-llama/Llama-3.3-70B-Instruct',
            system_prompt: 'You are an official enterprise customer support agent for our company. Answer politely and concisely.',
            user_prompt: '{{ $node["Telegram Trigger"].text }}',
          },
          inputs: NODE_REGISTRY.hf_router.inputs,
          outputs: NODE_REGISTRY.hf_router.outputs,
        },
      },
      {
        id: 'node_tg_rep',
        type: 'telegram_reply',
        position: { x: 900, y: 200 },
        data: {
          label: 'Telegram Reply',
          category: 'actions',
          type: 'telegram_reply',
          status: 'idle',
          subtitle: 'Reply Inbound Chat',
          config: {
            chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}',
            message_template: '{{ $node["HuggingFace Router"].response_text }}',
          },
          inputs: NODE_REGISTRY.telegram_reply.inputs,
          outputs: NODE_REGISTRY.telegram_reply.outputs,
        },
      },
    ],
    edges: [
      {
        id: 'edge_tg_1',
        source: 'node_tg_trig',
        sourceHandle: 'text',
        target: 'node_hf_llama_bot',
        targetHandle: 'user_prompt',
        type: 'customEdge',
        data: { color: '#38bdf8' },
      },
      {
        id: 'edge_tg_2',
        source: 'node_hf_llama_bot',
        sourceHandle: 'response_text',
        target: 'node_tg_rep',
        targetHandle: 'text',
        type: 'customEdge',
        data: { color: '#8b5cf6' },
      },
    ],
  },
  {
    id: 'tpl_whatsapp_flux',
    name: '🎨 WhatsApp FLUX.1 Image Pipeline (Gradio Space)',
    category: 'image',
    description: 'Transform WhatsApp text prompts into 1024x1024 photorealistic digital artwork using Black Forest Labs FLUX.1 on Hugging Face Spaces.',
    iconName: 'Image',
    badgeText: 'FLUX.1 • Free Gradio Space',
    hfGuide: {
      summary: 'Generates photo-art via Black Forest Labs FLUX.1 hosted on community ZeroGPU Spaces, returning direct image media to WhatsApp.',
      hfModelSlug: 'black-forest-labs/FLUX.1-schnell',
      hardwareTier: 'ZeroGPU Community Space',
      stepByStep: [
        'Step A: Connect WhatsApp Cloud API credentials in Settings.',
        'Step B: Users message prompts like "cyberpunk samurai in Tokyo" to your WhatsApp number.',
        'Step C: Workflow invokes FLUX.1 Gradio Space client with sub-second generation.',
        'Step D: Generated image URL is packaged into a media payload and sent to WhatsApp.',
      ],
      docUrl: 'https://huggingface.co/black-forest-labs/FLUX.1-schnell',
    },
    nodes: [
      {
        id: 'node_wa_trig',
        type: 'whatsapp_trigger',
        position: { x: 100, y: 200 },
        data: {
          label: 'WhatsApp Trigger',
          category: 'triggers',
          type: 'whatsapp_trigger',
          status: 'idle',
          subtitle: 'Meta Cloud API Inbound',
          config: NODE_REGISTRY.whatsapp_trigger.defaultConfig,
          inputs: NODE_REGISTRY.whatsapp_trigger.inputs,
          outputs: NODE_REGISTRY.whatsapp_trigger.outputs,
        },
      },
      {
        id: 'node_gradio_flux',
        type: 'gradio_space',
        position: { x: 500, y: 200 },
        data: {
          label: 'Gradio ZeroGPU Space',
          category: 'models',
          type: 'gradio_space',
          status: 'idle',
          subtitle: 'black-forest-labs/FLUX.1-schnell',
          config: {
            ...NODE_REGISTRY.gradio_space.defaultConfig,
            space_slug: 'black-forest-labs/FLUX.1-schnell',
            api_name: '/predict',
          },
          inputs: NODE_REGISTRY.gradio_space.inputs,
          outputs: NODE_REGISTRY.gradio_space.outputs,
        },
      },
      {
        id: 'node_wa_reply',
        type: 'whatsapp_reply',
        position: { x: 900, y: 200 },
        data: {
          label: 'WhatsApp Reply',
          category: 'actions',
          type: 'whatsapp_reply',
          status: 'idle',
          subtitle: 'Send Image Media',
          config: NODE_REGISTRY.whatsapp_reply.defaultConfig,
          inputs: NODE_REGISTRY.whatsapp_reply.inputs,
          outputs: NODE_REGISTRY.whatsapp_reply.outputs,
        },
      },
    ],
    edges: [
      {
        id: 'edge_wa_1',
        source: 'node_wa_trig',
        sourceHandle: 'message_body',
        target: 'node_gradio_flux',
        targetHandle: 'prompt',
        type: 'customEdge',
        data: { color: '#22c55e' },
      },
      {
        id: 'edge_wa_2',
        source: 'node_gradio_flux',
        sourceHandle: 'image_url',
        target: 'node_wa_reply',
        targetHandle: 'media_url',
        type: 'customEdge',
        data: { color: '#ec4899' },
      },
    ],
  },
  {
    id: 'tpl_deepseek_r1_reasoning',
    name: '🧠 DeepSeek R1 Reasoning Summarizer & Fact Extractor',
    category: 'reasoning',
    description: 'Deep mathematical and logical reasoning pipeline powered by DeepSeek-R1-Distill-Qwen-32B — delivers structured step-by-step thinking traces.',
    iconName: 'Cpu',
    badgeText: 'DeepSeek R1 • 100% Free',
    hfGuide: {
      summary: 'High-IQ reasoning model distilled by DeepSeek AI on Qwen 32B architecture. Provides chain-of-thought mathematical and logic verification.',
      hfModelSlug: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Select DeepSeek-R1-Distill-Qwen-32B as your target LLM.',
        'Step B: Configure prompt template to request chain-of-thought analysis.',
        'Step C: Model evaluates logical steps and returns <think> reasoning blocks along with verified solutions.',
      ],
      docUrl: 'https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
    },
    nodes: [
      {
        id: 'node_trig_poll',
        type: 'telegram_trigger',
        position: { x: 100, y: 200 },
        data: {
          label: 'Telegram Trigger',
          category: 'triggers',
          type: 'telegram_trigger',
          status: 'idle',
          subtitle: 'Reasoning Inbound Task',
          config: NODE_REGISTRY.telegram_trigger.defaultConfig,
          inputs: NODE_REGISTRY.telegram_trigger.inputs,
          outputs: NODE_REGISTRY.telegram_trigger.outputs,
        },
      },
      {
        id: 'node_ds_r1',
        type: 'hf_router',
        position: { x: 500, y: 200 },
        data: {
          label: 'HuggingFace Router',
          category: 'models',
          type: 'hf_router',
          status: 'idle',
          subtitle: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
          config: {
            ...NODE_REGISTRY.hf_router.defaultConfig,
            model_id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
            system_prompt: 'You are DeepSeek-R1, an expert reasoning and logical analysis engine. Break down complex questions step by step.',
            user_prompt: '{{ $node["Telegram Trigger"].text }}',
          },
          inputs: NODE_REGISTRY.hf_router.inputs,
          outputs: NODE_REGISTRY.hf_router.outputs,
        },
      },
      {
        id: 'node_reply_ds',
        type: 'telegram_reply',
        position: { x: 900, y: 200 },
        data: {
          label: 'Telegram Reply',
          category: 'actions',
          type: 'telegram_reply',
          status: 'idle',
          subtitle: 'Send Reasoning Answer',
          config: {
            chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}',
            message_template: '🧠 **DeepSeek-R1 Reasoning Analysis**:\n\n{{ $node["HuggingFace Router"].response_text }}',
          },
          inputs: NODE_REGISTRY.telegram_reply.inputs,
          outputs: NODE_REGISTRY.telegram_reply.outputs,
        },
      },
    ],
    edges: [
      {
        id: 'edge_ds_1',
        source: 'node_trig_poll',
        sourceHandle: 'text',
        target: 'node_ds_r1',
        targetHandle: 'user_prompt',
        type: 'customEdge',
        data: { color: '#a855f7' },
      },
      {
        id: 'edge_ds_2',
        source: 'node_ds_r1',
        sourceHandle: 'response_text',
        target: 'node_reply_ds',
        targetHandle: 'text',
        type: 'customEdge',
        data: { color: '#ec4899' },
      },
    ],
  },
  {
    id: 'tpl_whisper_transcription',
    name: '🎙️ Whisper Voice Transcription Bot',
    category: 'audio',
    description: 'Transcribe voice messages and audio files using OpenAI Whisper Large v3 — 100% free on Hugging Face Inference API.',
    iconName: 'Mic',
    badgeText: 'Speech-to-Text • Free',
    hfGuide: {
      summary: 'Automated Automatic Speech Recognition (ASR) engine converting audio speech to structured text transcripts.',
      hfModelSlug: 'openai/whisper-large-v3',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Inbound voice message arrives via Telegram / WhatsApp trigger.',
        'Step B: Audio stream routes to Whisper Large v3 on Hugging Face.',
        'Step C: Model performs multilingual speech detection and returns text transcript.',
      ],
      docUrl: 'https://huggingface.co/openai/whisper-large-v3',
    },
    nodes: [
      { id: 'n1', type: 'telegram_trigger', position: { x: 80, y: 180 }, data: { label: 'Telegram Trigger', category: 'triggers', type: 'telegram_trigger', status: 'idle', subtitle: 'Voice/audio messages', config: NODE_REGISTRY.telegram_trigger.defaultConfig, inputs: NODE_REGISTRY.telegram_trigger.inputs, outputs: NODE_REGISTRY.telegram_trigger.outputs } },
      { id: 'n2', type: 'hf_router', position: { x: 480, y: 180 }, data: { label: 'Whisper ASR', category: 'models', type: 'hf_router', status: 'idle', subtitle: 'openai/whisper-large-v3', config: { ...NODE_REGISTRY.hf_router.defaultConfig, model_id: 'openai/whisper-large-v3', system_prompt: 'Transcribe the audio accurately. Return only the transcript.', user_prompt: '{{ $node["Telegram Trigger"].text }}' }, inputs: NODE_REGISTRY.hf_router.inputs, outputs: NODE_REGISTRY.hf_router.outputs } },
      { id: 'n3', type: 'telegram_reply', position: { x: 880, y: 180 }, data: { label: 'Telegram Reply', category: 'actions', type: 'telegram_reply', status: 'idle', subtitle: 'Send Transcript', config: { chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}', message_template: '🎙️ **Whisper Transcript:**\n\n{{ $node["Whisper ASR"].response_text }}' }, inputs: NODE_REGISTRY.telegram_reply.inputs, outputs: NODE_REGISTRY.telegram_reply.outputs } },
    ],
    edges: [
      { id: 'e1', source: 'n1', sourceHandle: 'text', target: 'n2', targetHandle: 'user_prompt', type: 'customEdge', data: { color: '#38bdf8' } },
      { id: 'e2', source: 'n2', sourceHandle: 'response_text', target: 'n3', targetHandle: 'text', type: 'customEdge', data: { color: '#8b5cf6' } },
    ],
  },
  {
    id: 'tpl_code_assistant',
    name: '💻 DeepSeek R1 Code Assistant',
    category: 'chatbot',
    description: 'AI coding assistant powered by DeepSeek-R1-Distill-Qwen-32B — solves coding problems, explains code, and writes clean solutions.',
    iconName: 'Code2',
    badgeText: 'DeepSeek R1 • Free',
    hfGuide: {
      summary: 'Code generation and debugging assistant capable of writing idiomatic TypeScript, Python, Rust, and Go.',
      hfModelSlug: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Send coding prompts or error logs to the chatbot.',
        'Step B: DeepSeek R1 decomposes logic, fixes syntax, and outputs runnable code blocks.',
      ],
      docUrl: 'https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
    },
    nodes: [
      { id: 'n1', type: 'telegram_trigger', position: { x: 80, y: 180 }, data: { label: 'Telegram Trigger', category: 'triggers', type: 'telegram_trigger', status: 'idle', subtitle: 'Code questions', config: NODE_REGISTRY.telegram_trigger.defaultConfig, inputs: NODE_REGISTRY.telegram_trigger.inputs, outputs: NODE_REGISTRY.telegram_trigger.outputs } },
      { id: 'n2', type: 'hf_router', position: { x: 480, y: 180 }, data: { label: 'DeepSeek R1', category: 'models', type: 'hf_router', status: 'idle', subtitle: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', config: { ...NODE_REGISTRY.hf_router.defaultConfig, model_id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', system_prompt: 'You are an expert full-stack software engineer. Provide concise code solutions with explanations.', user_prompt: '{{ $node["Telegram Trigger"].text }}' }, inputs: NODE_REGISTRY.hf_router.inputs, outputs: NODE_REGISTRY.hf_router.outputs } },
      { id: 'n3', type: 'telegram_reply', position: { x: 880, y: 180 }, data: { label: 'Telegram Reply', category: 'actions', type: 'telegram_reply', status: 'idle', subtitle: 'Send Code Solution', config: { chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}', message_template: '💻 **Code Assistant Solution:**\n\n{{ $node["DeepSeek R1"].response_text }}' }, inputs: NODE_REGISTRY.telegram_reply.inputs, outputs: NODE_REGISTRY.telegram_reply.outputs } },
    ],
    edges: [
      { id: 'e1', source: 'n1', sourceHandle: 'text', target: 'n2', targetHandle: 'user_prompt', type: 'customEdge', data: { color: '#38bdf8' } },
      { id: 'e2', source: 'n2', sourceHandle: 'response_text', target: 'n3', targetHandle: 'text', type: 'customEdge', data: { color: '#a855f7' } },
    ],
  },
  {
    id: 'tpl_customer_support',
    name: '🤝 Llama Customer Support Agent',
    category: 'chatbot',
    description: 'Enterprise customer support agent using Meta Llama 3.3 70B Instruct — answers customer inquiries with domain knowledge.',
    iconName: 'Bot',
    badgeText: 'Llama 3.3 • Free',
    hfGuide: {
      summary: 'Tailored enterprise customer support agent using Llama 3.3 70B on Hugging Face Serverless Router.',
      hfModelSlug: 'meta-llama/Llama-3.3-70B-Instruct',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Customize the System Prompt with company FAQs, return policies, and pricing.',
        'Step B: Bot automatically answers user chats with accurate company guidelines.',
      ],
      docUrl: 'https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct',
    },
    nodes: [
      { id: 'n1', type: 'telegram_trigger', position: { x: 80, y: 180 }, data: { label: 'Telegram Trigger', category: 'triggers', type: 'telegram_trigger', status: 'idle', subtitle: 'Customer messages', config: NODE_REGISTRY.telegram_trigger.defaultConfig, inputs: NODE_REGISTRY.telegram_trigger.inputs, outputs: NODE_REGISTRY.telegram_trigger.outputs } },
      { id: 'n2', type: 'hf_router', position: { x: 480, y: 180 }, data: { label: 'Llama 3.3 70B', category: 'models', type: 'hf_router', status: 'idle', subtitle: 'meta-llama/Llama-3.3-70B-Instruct', config: { ...NODE_REGISTRY.hf_router.defaultConfig, model_id: 'meta-llama/Llama-3.3-70B-Instruct', system_prompt: 'You are an enterprise customer support agent. Be helpful, professional, and accurate.', user_prompt: '{{ $node["Telegram Trigger"].text }}' }, inputs: NODE_REGISTRY.hf_router.inputs, outputs: NODE_REGISTRY.hf_router.outputs } },
      { id: 'n3', type: 'telegram_reply', position: { x: 880, y: 180 }, data: { label: 'Telegram Reply', category: 'actions', type: 'telegram_reply', status: 'idle', subtitle: 'Send Support Reply', config: { chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}', message_template: '🤝 **Support Agent:**\n\n{{ $node["Llama 3.3 70B"].response_text }}' }, inputs: NODE_REGISTRY.telegram_reply.inputs, outputs: NODE_REGISTRY.telegram_reply.outputs } },
    ],
    edges: [
      { id: 'e1', source: 'n1', sourceHandle: 'text', target: 'n2', targetHandle: 'user_prompt', type: 'customEdge', data: { color: '#38bdf8' } },
      { id: 'e2', source: 'n2', sourceHandle: 'response_text', target: 'n3', targetHandle: 'text', type: 'customEdge', data: { color: '#22c55e' } },
    ],
  },
  {
    id: 'tpl_llama_vision',
    name: '👁️ Llama Vision Image Captioner',
    category: 'image',
    description: 'Analyze, describe, and extract text from images using Llama 3.2 11B Vision Instruct — multimodal AI on Hugging Face.',
    iconName: 'Eye',
    badgeText: 'Llama Vision • Free',
    hfGuide: {
      summary: 'Multimodal vision model capable of visual question answering, OCR text extraction, and scene captioning.',
      hfModelSlug: 'meta-llama/Llama-3.2-11B-Vision-Instruct',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Connect image URL input to Llama Vision router.',
        'Step B: Model outputs detailed visual descriptions and text analysis.',
      ],
      docUrl: 'https://huggingface.co/meta-llama/Llama-3.2-11B-Vision-Instruct',
    },
    nodes: [
      { id: 'n1', type: 'telegram_trigger', position: { x: 80, y: 180 }, data: { label: 'Telegram Trigger', category: 'triggers', type: 'telegram_trigger', status: 'idle', subtitle: 'Image caption request', config: NODE_REGISTRY.telegram_trigger.defaultConfig, inputs: NODE_REGISTRY.telegram_trigger.inputs, outputs: NODE_REGISTRY.telegram_trigger.outputs } },
      { id: 'n2', type: 'hf_router', position: { x: 480, y: 180 }, data: { label: 'Llama Vision', category: 'models', type: 'hf_router', status: 'idle', subtitle: 'meta-llama/Llama-3.2-11B-Vision-Instruct', config: { ...NODE_REGISTRY.hf_router.defaultConfig, model_id: 'meta-llama/Llama-3.2-11B-Vision-Instruct', system_prompt: 'Describe the image in detail. Extract any visible text.', user_prompt: '{{ $node["Telegram Trigger"].text }}' }, inputs: NODE_REGISTRY.hf_router.inputs, outputs: NODE_REGISTRY.hf_router.outputs } },
      { id: 'n3', type: 'telegram_reply', position: { x: 880, y: 180 }, data: { label: 'Telegram Reply', category: 'actions', type: 'telegram_reply', status: 'idle', subtitle: 'Send Caption', config: { chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}', message_template: '👁️ **Image Analysis:**\n\n{{ $node["Llama Vision"].response_text }}' }, inputs: NODE_REGISTRY.telegram_reply.inputs, outputs: NODE_REGISTRY.telegram_reply.outputs } },
    ],
    edges: [
      { id: 'e1', source: 'n1', sourceHandle: 'text', target: 'n2', targetHandle: 'user_prompt', type: 'customEdge', data: { color: '#38bdf8' } },
      { id: 'e2', source: 'n2', sourceHandle: 'response_text', target: 'n3', targetHandle: 'text', type: 'customEdge', data: { color: '#06b6d4' } },
    ],
  },
  {
    id: 'tpl_whatsapp_flux_gen',
    name: '📲 WhatsApp FLUX.1 Image Generator',
    category: 'image',
    description: 'Automated WhatsApp bot that generates photorealistic images using FLUX.1 Schnell and sends results directly to the user.',
    iconName: 'Image',
    badgeText: 'FLUX.1 • WhatsApp',
    hfGuide: {
      summary: 'Turn WhatsApp messages into FLUX.1 AI artworks and reply directly with high-resolution image links.',
      hfModelSlug: 'black-forest-labs/FLUX.1-schnell',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Setup WhatsApp Cloud API endpoint.',
        'Step B: Inbound message prompt routes to FLUX.1 Schnell.',
        'Step C: High-resolution image generated and delivered to WhatsApp.',
      ],
      docUrl: 'https://huggingface.co/black-forest-labs/FLUX.1-schnell',
    },
    nodes: [
      { id: 'n1', type: 'whatsapp_trigger', position: { x: 80, y: 180 }, data: { label: 'WhatsApp Trigger', category: 'triggers', type: 'whatsapp_trigger', status: 'idle', subtitle: 'Image prompt from user', config: NODE_REGISTRY.whatsapp_trigger.defaultConfig, inputs: NODE_REGISTRY.whatsapp_trigger.inputs, outputs: NODE_REGISTRY.whatsapp_trigger.outputs } },
      { id: 'n2', type: 'hf_image_gen', position: { x: 480, y: 180 }, data: { label: 'FLUX.1 Schnell', category: 'models', type: 'hf_image_gen', status: 'idle', subtitle: 'black-forest-labs/FLUX.1-schnell', config: { ...NODE_REGISTRY.hf_image_gen.defaultConfig, model_id: 'black-forest-labs/FLUX.1-schnell', prompt_template: '{{ $node["WhatsApp Trigger"].message_body }}' }, inputs: NODE_REGISTRY.hf_image_gen.inputs, outputs: NODE_REGISTRY.hf_image_gen.outputs } },
      { id: 'n3', type: 'whatsapp_reply', position: { x: 880, y: 180 }, data: { label: 'WhatsApp Reply', category: 'actions', type: 'whatsapp_reply', status: 'idle', subtitle: 'Send image result', config: { ...NODE_REGISTRY.whatsapp_reply.defaultConfig }, inputs: NODE_REGISTRY.whatsapp_reply.inputs, outputs: NODE_REGISTRY.whatsapp_reply.outputs } },
    ],
    edges: [
      { id: 'e1', source: 'n1', sourceHandle: 'message_body', target: 'n2', targetHandle: 'user_prompt', type: 'customEdge', data: { color: '#25d366' } },
      { id: 'e2', source: 'n2', sourceHandle: 'image_url', target: 'n3', targetHandle: 'text', type: 'customEdge', data: { color: '#a855f7' } },
    ],
  },
  {
    id: 'tpl_telegram_video_gen',
    name: '🎥 ZeroScope AI Video Generation Bot',
    category: 'image',
    description: 'Generate high-definition AI video clips directly from Telegram prompts using ZeroScope v2 text-to-video.',
    iconName: 'Video',
    badgeText: 'ZeroScope • Video • Free',
    hfGuide: {
      summary: 'Prompt-aware text-to-video pipeline running ZeroScope v2 on Hugging Face free inference infrastructure.',
      hfModelSlug: 'cerspense/zeroscope_v2_576w',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Telegram user sends a prompt like "video about pyramids".',
        'Step B: ZeroScope generates a clean static scene preview and direct MP4 link.',
        'Step C: Bot replies with playable video link.',
      ],
      docUrl: 'https://huggingface.co/cerspense/zeroscope_v2_576w',
    },
    nodes: [
      { id: 'n1', type: 'telegram_trigger', position: { x: 80, y: 180 }, data: { label: 'Telegram Trigger', category: 'triggers', type: 'telegram_trigger', status: 'idle', subtitle: 'Video prompt from user', config: NODE_REGISTRY.telegram_trigger.defaultConfig, inputs: NODE_REGISTRY.telegram_trigger.inputs, outputs: NODE_REGISTRY.telegram_trigger.outputs } },
      { id: 'n2', type: 'hf_video_gen', position: { x: 480, y: 180 }, data: { label: 'ZeroScope Video', category: 'models', type: 'hf_video_gen', status: 'idle', subtitle: 'cerspense/zeroscope_v2_576w', config: { ...NODE_REGISTRY.hf_video_gen.defaultConfig, user_prompt: '{{ $node["Telegram Trigger"].text }}' }, inputs: NODE_REGISTRY.hf_video_gen.inputs, outputs: NODE_REGISTRY.hf_video_gen.outputs } },
      { id: 'n3', type: 'telegram_reply', position: { x: 880, y: 180 }, data: { label: 'Telegram Reply', category: 'actions', type: 'telegram_reply', status: 'idle', subtitle: 'Send Video Stream', config: { chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}', message_template: '🎥 **Generated Video:**\n{{ $node["ZeroScope Video"].video_url }}' }, inputs: NODE_REGISTRY.telegram_reply.inputs, outputs: NODE_REGISTRY.telegram_reply.outputs } },
    ],
    edges: [
      { id: 'e1', source: 'n1', sourceHandle: 'text', target: 'n2', targetHandle: 'user_prompt', type: 'customEdge', data: { color: '#38bdf8' } },
      { id: 'e2', source: 'n2', sourceHandle: 'video_url', target: 'n3', targetHandle: 'text', type: 'customEdge', data: { color: '#ec4899' } },
    ],
  },
  {
    id: 'tpl_zero_shot_router',
    name: '🧠 Zero-Shot AI Intent Router & Smart Action Pipeline',
    category: 'reasoning',
    description: 'Classify any incoming Telegram/WhatsApp message into dynamic arbitrary labels with zero training, routing requests to AI support, image generation, or sales.',
    iconName: 'Zap',
    badgeText: 'Zero-Shot • BART MNLI • Free',
    hfGuide: {
      summary: 'State-of-the-art Natural Language Inference pipeline evaluating candidate labels in real-time with zero fine-tuning.',
      hfModelSlug: 'facebook/bart-large-mnli',
      hardwareTier: 'Serverless Inference API (Free)',
      stepByStep: [
        'Step A: Inbound message received from Telegram or WhatsApp.',
        'Step B: Zero-Shot model evaluates arbitrary candidate labels (support, billing, image_request, video_request).',
        'Step C: High-confidence prediction triggers tailored downstream action.',
        'Step D: Response sent back to user with intent category tag.',
      ],
      docUrl: 'https://huggingface.co/facebook/bart-large-mnli',
    },
    nodes: [
      { id: 'n1', type: 'telegram_trigger', position: { x: 80, y: 180 }, data: { label: 'Telegram Trigger', category: 'triggers', type: 'telegram_trigger', status: 'idle', subtitle: 'User inquiry message', config: NODE_REGISTRY.telegram_trigger.defaultConfig, inputs: NODE_REGISTRY.telegram_trigger.inputs, outputs: NODE_REGISTRY.telegram_trigger.outputs } },
      { id: 'n2', type: 'hf_zero_shot', position: { x: 480, y: 180 }, data: { label: 'Zero-Shot Classifier', category: 'models', type: 'hf_zero_shot', status: 'idle', subtitle: 'facebook/bart-large-mnli', config: { ...NODE_REGISTRY.hf_zero_shot.defaultConfig, text: '{{ $node["Telegram Trigger"].text }}' }, inputs: NODE_REGISTRY.hf_zero_shot.inputs, outputs: NODE_REGISTRY.hf_zero_shot.outputs } },
      { id: 'n3', type: 'telegram_reply', position: { x: 880, y: 180 }, data: { label: 'Telegram Reply', category: 'actions', type: 'telegram_reply', status: 'idle', subtitle: 'Send Routed Response', config: { chat_id_template: '{{ $node["Telegram Trigger"].chat_id }}', message_template: '🎯 **Zero-Shot Intent Detected:** `{{ $node["Zero-Shot Classifier"].top_label }}`\nConfidence: {{ $node["Zero-Shot Classifier"].confidence }}\n\nProcessed with zero-shot model inference.' }, inputs: NODE_REGISTRY.telegram_reply.inputs, outputs: NODE_REGISTRY.telegram_reply.outputs } },
    ],
    edges: [
      { id: 'e1', source: 'n1', sourceHandle: 'text', target: 'n2', targetHandle: 'text', type: 'customEdge', data: { color: '#38bdf8' } },
      { id: 'e2', source: 'n2', sourceHandle: 'top_label', target: 'n3', targetHandle: 'text', type: 'customEdge', data: { color: '#10b981' } },
    ],
  },
];
